### PR TITLE
add missing deepspeed options

### LINKED ISSUE #57: Deepspeed CPU offloader isnt being passed
Right now if you enable cpu offloading it doesn't actually pass the `--cpu_offload_optimizer` flag or any of the other deepspeed specific options.

### LINKED ISSUE #62: Add separate "save_samples_ds" argument into the interface
Currently the only interface option is for regular hf format checkpointing. There needs to be an option for ds universal checkpoints for auto-resume

### PR DESCRIPTION
**Pull request by RobotSail**
Fixes #62 
Fixes #57 

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

### CODE REVIEW

**Comment by aldopareja** [comment]
do we really want to expose that?, we might as well just ask the user to provide a json file with the deepspeed config they want.

**Comment by aldopareja** [comment]
but I think in general exposing so much to the user is overwhelming, no one really changes these options anyway, and if you do, then you can also just hard code it in the code instead of using a parameter.

**Comment by kdvalin** [comment]
For CPU Offload Memory Pinning, [this constructor](https://github.com/instructlab/training/blob/a9f97c8771d421afc085f123806467ca39ac0131/src/instructlab/training/main_ds.py#L243) needs `cpu_offload_optimizer_pin_memory=args.cpu_offload_optimizer_pin_memory,` added.  There seems to be other options missing from this as well.

**Comment by RobotSail** [comment]
@aldopareja Yes this is something that should be configurable. In the future we can look at exposing the full config, but right now much of this stuff is conditional so we're constructing it ourselves.

**Comment by Maxusmusti** [comment]
yeah, @aldopareja these options are actually important for us to expose for the performance team:
```
cpu_offload_optimizer
cpu_offload_optimizer_ratio
cpu_offload_optimizer_pin_memory
```
but agreed that we don't need to expose everything as it can get quickly overwhelming. I think the current state of this PR is good

**Review by Maxusmusti — APPROVED** [review]
LGTM

**Pull request merged**
