### PR TITLE
Import initial CI configuration

### PR DESCRIPTION
**Pull request by russellb**
- **Import initial CI configuration**
- **Apply `tox -e ruff` formatting changes**
- **Remove unused Python imports**
- **Resolve lint warnings about redefining variables**
- **Resolve lint warnings about unused arguments**
- **Make pylint complete successfully**
- **README.md: Drop "BACKEND" from the title**

commit e489e17d1cf0c03001b0202552a01b323727724f
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 07:48:01 2024 -0400

    Import initial CI configuration
    
    Import jobs to run
    
    - linting of github workflows (actionlint)
    - python formatting and linting
    - spell checking
    - markdown linting
    
    This also includes requirements*.txt files.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 76d83f082f1222e0b2186f47f4c70a54f945b2ad
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 07:48:22 2024 -0400

    Apply `tox -e ruff` formatting changes
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 29fe072174ff1f8598befc3985a8d2a62b30222a
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 07:55:07 2024 -0400

    Remove unused Python imports
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit e88162f92c99ce0dd9040918f672bcd6367150bc
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 08:02:24 2024 -0400

    Resolve lint warnings about redefining variables
    
    For example:
    
    ```
    main_ds.py:50:16: W0621: Redefining name 'args' from outer scope (line 280) (redefined-outer-name)
    main_ds.py:100:10: W0621: Redefining name 'args' from outer scope (line 280) (redefined-outer-name)
    main_ds.py:188:9: W0621: Redefining name 'args' from outer scope (line 280) (redefined-outer-name)
    tokenizer_utils.py:38:24: W0621: Redefining name 'SPECIAL_TOKENS' from outer scope (line 22) (redefined-outer-name)
    tokenizer_utils.py:38:55: W0621: Redefining name 'CHAT_TEMPLATE' from outer scope (line 24) (redefined-outer-name)
    data_process.py:173:9: W0621: Redefining name 'args' from outer scope (line 271) (redefined-outer-name)
    ```
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit b6adf5d3df0ce471be4133721cb55f34188cc832
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 08:05:24 2024 -0400

    Resolve lint warnings about unused arguments
    
    By prefixing the unused arguments with an underscore, pylint
    understands this as a hint that we intentionally ignore the argument.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 45003e12163b3d1276388dfbd5194adf60e3378c
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed May 1 08:12:21 2024 -0400

    Make pylint complete successfully
    
    Drop a couple of f-strings without any interpolation, set an encoding
    type on `open()`, and update the pylint configuration to ignore all
    remaining warnings for now.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 851d73a3b64c492376dc591a11bac3116356deec
Author: Russell Bryant <rbryant@redhat.com>
Date:   Mon Apr 29 10:08:19 2024 -0400

    README.md: Drop "BACKEND" from the title
    
    This code is not backend-specific, so drop it from the readme title.
    While we're at it, capitalize DeepSpeed as the upstream project does
    it.
    
    While we're at it, add badges to README.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by russellb** [comment]
The jobs are running on my fork, so you can see them pass here: https://github.com/russellb/instructlab-training/actions

This is split up into separate commits to make it easier to review.  The bulk import of config that doesn't touch code is the first commit. Code changes are split apart so you can more easily see changes from the formatting tool vs "real" code changes, along with their explanations.

**Review by nathan-weinberg — APPROVED** [review]
LGTM

**Comment by nathan-weinberg** [comment]
@russellb think we should revisit this for the librarification?

**Comment by russellb** [comment]
> @russellb think we should revisit this for the librarification?

imo yes

**Comment by russellb** [comment]
@nathan-weinberg are you interested in taking this over?

**Comment by nathan-weinberg** [comment]
@russellb I can if it's fine with @RobotSail @Maxusmusti and @JamesKunstle! probably open a new PR with the same config being used in the other `sdg` and `eval` libs

**Comment by aldopareja** [comment]
shall we renew this PR?

**Comment by RobotSail** [comment]
We should get rid of spell-checking. It will be really annoying to constantly update it with all of the new terminology that it won't have.

**Review by RobotSail — CHANGES_REQUESTED** [review]
Thank you for this PR. Other than spell-checking, everything here will be really useful to have in this repo.

**Comment by nathan-weinberg** [comment]
Spellcheck is present in the other repos, so it should be included here as well. Better to stay consistent, and it really isn't that much overhead.

**Comment by russellb** [comment]
> Spellcheck is present in the other repos, so it should be included here as well. Better to stay consistent, and it really isn't that much overhead.

I'd agree updating the list can be annoying. I'd like to automating synching the files across all repos at some point to help minimize necessary updates.

but it does catch real mistakes too.

**Comment by nathan-weinberg** [comment]
I'm going to open a new PR as I'll be taking this over from @russellb - I will add the usual suspects to the review for the new one once it's ready

**Pull request closed without merging**
