### PR TITLE
Ap/fix mistral template

### PR DESCRIPTION
**Pull request by aldopareja**
this builds on top of #169, it changes the way we treat system, assistant and user tokens, and assume they are always lists (which could be empty) or single element. We are loosing testing of the alternation between user and assistant. But the jinja template of mistral enforces this, perhaps we could do the same with granite.

### CODE REVIEW

**Comment by aldopareja** [comment]
@Maxusmusti @JamesKunstle @RobotSail  this fixes #182

**Comment by aldopareja** [comment]
fixes #184

**Comment by Maxusmusti** [comment]
@aldo-pareja can you rebase this on current main? (which now includes #169 )

**Comment by Maxusmusti** [comment]
Closing as these changes are introduced in #213

**Pull request closed without merging**
