### PR TITLE
chore: change references to "master" to "main"

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Fixes https://github.com/instructlab/training/issues/148

### CODE REVIEW

**Review by Maxusmusti — CHANGES_REQUESTED** [review]
Thanks for the PR @nathan-weinberg! Unfortunately, this will actually break with the current version of pytorch. While we control our local vars, the environment variables are actually set/controlled by torchrun, meaning changing the `os.getenv` calls to look for different env vars will cause them to find nothing. We can update this PR for now just to rename our local variables and leave the env vars as-is, or we can wait for one of the following:
 - upstream torch updates their language
 - we create a fork of torch that changes these fields (likely fragile due to potential requirements to support nvidia pytorch)

**Comment by nathan-weinberg** [comment]
> Thanks for the PR @nathan-weinberg! Unfortunately, this will actually break with the current version of pytorch. While we control our local vars, the environment variables are actually set/controlled by torchrun, meaning changing the `os.getenv` calls to look for different env vars will cause them to find nothing. We can update this PR for now just to rename our local variables and leave the env vars as-is, or we can wait for one of the following:
> 
>     * upstream torch updates their language
> 
>     * we create a fork of torch that changes these fields (likely fragile due to potential requirements to support nvidia pytorch)

I will update the PR to just change the local variable names!

**Comment by RobotSail** [comment]
I don't think that we should update the local variable names, the reason being that it allows us to be consistent with the upstream and makes it easier to debug issues. By staying consistent, we'll make it easier for users and consumers of the training repo to know exactly what each variable is. The `TorchrunArguments` object had its keys specifically designed to be in parity with what `torchrun` uses, e.g. using `nproc_per_node` rather than the easier `num_gpus`.

**Comment by nathan-weinberg** [comment]
@RobotSail That logic is sound - I'm also happy to close this PR but only if we also close the related issue - we need to trim down these backlogs and if we're not going to do the issues they should be closed (like I said I'm fine with either approach!)

**Comment by RobotSail** [comment]
@nathan-weinberg That's totally fine, we can close the other issue then. Thank you for staying on top of the backlog!

**Comment by nathan-weinberg** [comment]
@RobotSail for sure - I will close this - can you close the issue with the explanation you have in the PR so it's tracked there?

**Comment by RobotSail** [comment]
@nathan-weinberg done!

**Pull request closed without merging**
