### PR TITLE
feat: add e2e test for instructlab CI

### PR DESCRIPTION
**Pull request by RobotSail**
This commit adds a modified version of the E2E NVIDIA T4 workflow from the instructlab/instructlab
repository to automatically test new PRs against an NVIDIA box to see how they perform end-to-end.

This PR follows up work from the following PRs:

- https://github.com/instructlab/training/pull/69
- https://github.com/instructlab/training/pull/77

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

### CODE REVIEW

**Review by danmcp — APPROVED** [review]
LGTM

**Comment by RobotSail** [comment]
@danmcp Thanks, we already fixed it in another PR so will just need to rebase here.

**Comment by nathan-weinberg** [comment]
@RobotSail i remember you voiced concerns about the E2E script not living in this repo, is that still the case?

**Comment by RobotSail** [comment]
@nathan-weinberg

> i remember you voiced concerns about the E2E script not living in this repo, is that still the case?

Well the current workflow is not ideal but it is less work to have them live there for now until someone is interested in maintaining a separate set of tests in this repo. In the future if we decide to separate repos between upstream & downstream equivalents, the downstream should continue to rely on the tests in the https://github.com/instructlab/instructlab repo. The upstream version, should one exist, would drop this test and would instead rely on its own e2e tests.

**Comment by nathan-weinberg** [comment]
> @nathan-weinberg
> 
> > i remember you voiced concerns about the E2E script not living in this repo, is that still the case?
> 
> Well the current workflow is not ideal but it is less work to have them live there for now until someone is interested in maintaining a separate set of tests in this repo. In the future if we decide to separate repos between upstream & downstream equivalents, the downstream should continue to rely on the tests in the https://github.com/instructlab/instructlab repo. The upstream version, should one exist, would drop this test and would instead rely on its own e2e tests.

SGTM - we could even have a dedicated repo for upstream tests that other repos could pull from - this was done by the OCP org at one point: https://github.com/openshift/openshift-tests

**Review by nathan-weinberg — APPROVED** [review]

**Comment by RobotSail** [comment]
> we could even have a dedicated repo for upstream tests that other repos could pull from - this was done by the OCP org at one point: https://github.com/openshift/openshift-tests

Just to be clear, by upstream here you mean upstream relative to the other OCP repos and not upstream as in the upstream Kubernetes, right?

**Comment by nathan-weinberg** [comment]
Yes! So in our case it would be something like:
- a public repo for InstructLab tests that could be used anywhere upstream for testing within library repos (e.g. `instructlab-tests` with different tests that each lib can pull from)
- for tests for downstream projects such as RHEL AI, these tests _could_ be used but the development of them would focus on testing the InstructLab project first and foremost

**Comment by RobotSail** [comment]
Got it, that makes perfect sense.

**Pull request merged**
