### PR TITLE
Update main_ds.py

### PR DESCRIPTION
**Pull request by gxxu-ml**
don't error out on new granite class

### CODE REVIEW

**Review by RobotSail — APPROVED** [review]
LGTM

**Comment by RobotSail** [comment]
Thank you for the PR @gxxu-ml !

**Comment by RobotSail** [comment]
@mergeifyo rebase

**Comment by RobotSail** [comment]
@Mergify rebase

**Comment by JamesKunstle** [comment]
@gxxu-ml could you please rebase and make sure linting passes?

**Pull request closed without merging**
